Mpi emigration collision checking
esa/LADDS pull request #150
Opened 2022-08-16 15:06 UTC by gomezzz

# Description

- Added collision checks on the rank emigrants 
- Minor formatting and naming
- Fixed bug in collisionDetection around particles (endTraversal was missing leading to no collision being detected)
- Added setters for safe particle ids to aid tests (otherwise ids are not rankspecific in tests)
- Renamed regular grid decomp tests
- Added test for collision detection amongst leaving and incoming particles on MPI ranks
- Added checking for collision between currently migrating particles

## Related Pull Requests

- #138 

## Resolved Issues

- [x] fixes #145 

## How Has This Been Tested?

New tests, etc.

2022-08-16 15:07 UTC, gomezzz commented
@FG-TUM There is a problem with regular grid decomposition. Somehow, the particle communication is not correct and the particles moving from one rank to the other don't arrive. The test is currently failing for that. I don't really wanna spend time on this as we aren't using it right now anyways. Any suggestions?

2022-08-17 16:15 UTC, gomezzz commented
Tests are fixed in #151

2022-08-18 04:09 UTC, FG-TUM requested changes

2022-08-18 04:09 UTC, FG-TUM commented on src/ladds/distributedMemParallelization/ParticleMigrationHandler.h
> +    bool checkForInternalCollisions = false);
It's less error-prone to not use a default argument

2022-08-18 04:09 UTC, FG-TUM commented on tests/mpitestladds/SimulationTest.cpp
> - * @file SimulationTest.cpp
was this just deleted or moved?

2022-08-18 04:09 UTC, FG-TUM commented on tests/mpitestladds/distributedMemParallelization/RegularGridDecompositionTests.cpp
> + * @file RegularGridDecompositionTests.cpp
seems to have some overlap with AltitudeBasedDecompositionTests.cpp. Could probably benefit from some common super class for setup stuff.

2022-08-18 04:10 UTC, FG-TUM commented
> @FG-TUM There is a problem with regular grid decomposition. Somehow, the particle communication is not correct and the particles moving from one rank to the other don't arrive. The test is currently failing for that. I don't really wanna spend time on this as we aren't using it right now anyways. Any suggestions?

Either we fix it or we add a warning + issue when using it

2022-08-18 10:55 UTC, gomezzz commented on tests/mpitestladds/SimulationTest.cpp
> - * @file SimulationTest.cpp
didn't use git move

2022-08-18 17:09 UTC, FG-TUM commented
seems like the tests take forever now?

2022-08-18 19:03 UTC, gomezzz commented
> seems like the tests take forever now?

I think this happens if they fail, not sure why they don't just fail? If they pass however, they pass normally

2022-08-24 08:43 UTC, merged